apiVersion: v1
kind: Pod
metadata:
  name: example-pod
spec:
  containers:
  - name: busybox-ctr
    image: busybox:latest
    resources:
      requests:
        cpu: "300m"
        memory: "100Mi"
      limits:
        cpu: "500m"
        memory: "200Mi"
    command: ["sleep"]
    args: ["360"]




