apiVersion: v1
kind: Pod
metadata:
  name: svc-test
spec:
  containers:
  - name: cuda-container
    image: nvidia/cuda:12.2.0-runtime-ubuntu20.04
    resources:
      limits:
        nvidia.com/gpu: 1 # requesting 1 GPU
    command: ["sleep"]
    args: ["3600"]