apiVersion: v1
kind: ServiceAccount
metadata:
  name: fastpod-controller-manager
  namespace: kube-system

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fastpod-controller-manager
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["fastgshare.caps.in.tum"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["fastgshare.caps.in.tum"]
  resources: ["fastpods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods", "pods/log", "namespaces", "endpoints"]
  verbs: ["get", "list", "watch"]

---


